### ISSUE TITLE
yarn报错。。。

### ISSUE THREAD

**Issue by hm081333** [Indexyz/steam_2018_summer_game#5]
弱弱的问一句。。为什么要指定node版本为10.4.1。。。是有什么深意么？

**Comment by 5aaee9** [comment]
错误日志？

**Comment by hm081333** [comment]
yarn install v1.7.0
[1/5] Validating package.json...
error steam_2018_summer_game@1.0.0: The engine "node" is incompatible with this module. Expected version "6.14.3".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by hm081333** [comment]
只要你指定了node，电脑上装的node不是package上面指定的版本，就会抛出。

**Comment by hm081333** [comment]
应该在版本前面加>=或者<=，这样："node": ">=6.14.3"。
